name: Build and Test

permissions:
  contents: read
  actions: read
  checks: write

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node:
    name: "Node: Install and Lint"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # cache: 'npm' # TODO: what can this cache do a d can we get it for dotnet build too?
          node-version: 20.x

      - name: Install Node modules
        run: npm install
        working-directory: WebView

      - name: Run Eslint
        run: npm run lint
        continue-on-error: true
        working-directory: WebView

      - name: Save Code Linting Report JSON
        run: npm run lint:report
        continue-on-error: true
        working-directory: WebView

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: "eslint_report.json"

  dotnet:
    name: "Dotnet: Build and Test"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal  --logger "trx;LogFileName=test-results.trx"

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: false